/* Generated from docs/reference-fields.csv; source and license in NOTICE.md.
 * Signedness remains model-specific. */
#include "protocol/protocol.h"
const ghost_field_t ghost_fields[] = {
    {"battery_charge_total",
     "Battery Total charge",
     "kWh",
     "energy",
     "total_increasing",
     {72, 73},
     {70, 72},
     {78, 80},
     2,
     GHOST_I32,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"battery_discharge_total",
     "Battery Total discharge",
     "kWh",
     "energy",
     "total_increasing",
     {74, 75},
     {74, 76},
     {82, 84},
     2,
     GHOST_I32,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_import_total",
     "Grid Total import",
     "kWh",
     "energy",
     "total_increasing",
     {78, 80},
     {82, 86},
     {90, 94},
     2,
     GHOST_I32,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_frequency",
     "Grid Frequency",
     "Hz",
     "frequency",
     "measurement",
     {79, -1},
     {84, 0},
     {92, 0},
     1,
     GHOST_I16,
     0.01,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_export_total",
     "Grid Total export",
     "kWh",
     "energy",
     "total_increasing",
     {81, 82},
     {88, 90},
     {96, 98},
     2,
     GHOST_I32,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"load_consumption_total",
     "Load Total consumption",
     "kWh",
     "energy",
     "total_increasing",
     {85, 86},
     {96, 98},
     {104, 106},
     2,
     GHOST_I32,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"inverter_temperature_dc",
     "Inverter DC Temperature",
     "°C",
     "temperature",
     "measurement",
     {90, -1},
     {106, 0},
     {114, 0},
     1,
     GHOST_I16,
     0.1,
     -100,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"inverter_temperature_ac",
     "Inverter AC Temperature",
     "°C",
     "temperature",
     "measurement",
     {91, -1},
     {108, 0},
     {116, 0},
     1,
     GHOST_I16,
     0.1,
     -100,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_production_total",
     "PV Total production",
     "kWh",
     "energy",
     "total_increasing",
     {96, 97},
     {118, 120},
     {126, 128},
     2,
     GHOST_I32,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"battery_capacity",
     "Battery Capacity",
     "Ah",
     "",
     "measurement",
     {107, -1},
     {140, 0},
     {148, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_voltage_1",
     "PV Voltage 1",
     "V",
     "voltage",
     "measurement",
     {109, -1},
     {144, 0},
     {152, 0},
     1,
     GHOST_I16,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_current_1",
     "PV Current 1",
     "A",
     "current",
     "measurement",
     {110, -1},
     {146, 0},
     {154, 0},
     1,
     GHOST_I16,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_voltage_2",
     "PV Voltage 2",
     "V",
     "voltage",
     "measurement",
     {111, -1},
     {148, 0},
     {156, 0},
     1,
     GHOST_I16,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_current_2",
     "PV Current 2",
     "A",
     "current",
     "measurement",
     {112, -1},
     {150, 0},
     {158, 0},
     1,
     GHOST_I16,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_voltage_3",
     "PV Voltage 3",
     "V",
     "voltage",
     "measurement",
     {113, -1},
     {152, 0},
     {160, 0},
     1,
     GHOST_I16,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_current_3",
     "PV Current 3",
     "A",
     "current",
     "measurement",
     {114, -1},
     {154, 0},
     {162, 0},
     1,
     GHOST_I16,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_voltage",
     "Grid Voltage",
     "V",
     "voltage",
     "measurement",
     {150, -1},
     {176, 0},
     {184, 0},
     1,
     GHOST_I16,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"load_voltage",
     "Load Voltage",
     "V",
     "voltage",
     "measurement",
     {154, -1},
     {184, 0},
     {192, 0},
     1,
     GHOST_I16,
     0.1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_current",
     "Grid Current",
     "A",
     "current",
     "measurement",
     {160, -1},
     {196, 0},
     {204, 0},
     1,
     GHOST_I16,
     0.01,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"load_current",
     "Load Current",
     "A",
     "current",
     "measurement",
     {164, -1},
     {204, 0},
     {212, 0},
     1,
     GHOST_I16,
     0.01,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_power_l1",
     "Grid Power L1",
     "W",
     "power",
     "measurement",
     {167, -1},
     {210, 0},
     {218, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_power",
     "Grid Power",
     "W",
     "power",
     "measurement",
     {169, -1},
     {214, 0},
     {222, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_power_ct",
     "Grid Power CT",
     "W",
     "power",
     "measurement",
     {172, -1},
     {220, 0},
     {228, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"inverter_power",
     "Inverter Power",
     "W",
     "power",
     "measurement",
     {175, -1},
     {226, 0},
     {234, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"load_power",
     "Load Power",
     "W",
     "power",
     "measurement",
     {178, -1},
     {232, 0},
     {240, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"battery_temperature",
     "Battery Temperature",
     "°C",
     "temperature",
     "measurement",
     {182, -1},
     {240, 0},
     {248, 0},
     1,
     GHOST_I16,
     0.1,
     -100,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"battery_voltage",
     "Battery Voltage",
     "V",
     "voltage",
     "measurement",
     {183, -1},
     {242, 0},
     {250, 0},
     1,
     GHOST_I16,
     0.01,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"battery_soc",
     "Battery SOC",
     "%",
     "battery",
     "measurement",
     {184, -1},
     {244, 0},
     {252, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_power_1",
     "PV Power 1",
     "W",
     "power",
     "measurement",
     {186, -1},
     {248, 0},
     {256, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_power_2",
     "PV Power 2",
     "W",
     "power",
     "measurement",
     {187, -1},
     {250, 0},
     {258, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_power_3",
     "PV Power 3",
     "W",
     "power",
     "measurement",
     {188, -1},
     {252, 0},
     {260, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"battery_power",
     "Battery Power",
     "W",
     "power",
     "measurement",
     {190, -1},
     {256, 0},
     {264, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"battery_current",
     "Battery Current",
     "A",
     "current",
     "measurement",
     {191, -1},
     {258, 0},
     {266, 0},
     1,
     GHOST_I16,
     0.01,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"load_frequency",
     "Load Frequency",
     "Hz",
     "frequency",
     "measurement",
     {192, -1},
     {260, 0},
     {268, 0},
     1,
     GHOST_I16,
     0.01,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"grid_connected",
     "Grid Connected",
     "",
     "",
     "measurement",
     {194, -1},
     {264, 0},
     {272, 0},
     1,
     GHOST_I16,
     1,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"bms_charge_voltage",
     "BMS Charge Voltage",
     "V",
     "voltage",
     "measurement",
     {-1, -1},
     {276, 0},
     {286, 0},
     1,
     GHOST_I16,
     0.01,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"bms_charge_limit_current",
     "BMS Charge Limit Current",
     "A",
     "current",
     "measurement",
     {-1, -1},
     {280, 0},
     {290, 0},
     1,
     GHOST_I16,
     1.0,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"bms_discharge_limit_current",
     "BMS Discharge Limit Current",
     "A",
     "current",
     "measurement",
     {-1, -1},
     {282, 0},
     {292, 0},
     1,
     GHOST_I16,
     1.0,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"bms_voltage",
     "BMS Voltage",
     "V",
     "voltage",
     "measurement",
     {-1, -1},
     {286, 0},
     {296, 0},
     1,
     GHOST_I16,
     0.01,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"bms_current",
     "BMS Current",
     "A",
     "current",
     "measurement",
     {-1, -1},
     {288, 0},
     {298, 0},
     1,
     GHOST_I16,
     1.0,
     0,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"bms_temperature",
     "BMS Temperature",
     "°C",
     "temperature",
     "measurement",
     {-1, -1},
     {290, 0},
     {300, 0},
     1,
     GHOST_I16,
     0.1,
     -100,
     0xffffffff,
     "Single-phase reference; see NOTICE.md",
     NULL,
     {0, 0}},
    {"pv_power",
     "PV Power",
     "W",
     "power",
     "measurement",
     {-1, -1},
     {0, 0},
     {0, 0},
     0,
     GHOST_I16,
     1,
     0,
     0,
     "Derived sum; all source values required",
     "pv_power_1 pv_power_2 pv_power_3",
     {0, 0}},
#include "register_extra.inc"
};
const size_t ghost_field_count = sizeof(ghost_fields) / sizeof(ghost_fields[0]);
_Static_assert(sizeof(ghost_fields) / sizeof(ghost_fields[0]) <= GHOST_FIELDS_MAX,
               "Increase field capacity");
