const {parseHTML}=require('linkedom');
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync('web/index.html','utf8');
const css=fs.readFileSync('web/style.css','utf8');
const {window}=parseHTML(html),document=window.document;
Object.defineProperty(window.HTMLElement.prototype,'elements',{get(){return this.querySelectorAll('input,select,button');}});
window.HTMLElement.prototype.scrollIntoView=function(){};
const config={version:9,imperial_units:false,packet_profiles:Array.from({length:8},(_,i)=>({slot:i+1,active:i<3,id:`packetoffset${String(i+1).padStart(3,'0')}`,name:i===0?'Legacy 292-byte packet':i===1?'Newer 302-byte packet':i===2?'Captured 306-byte packet':'',layout:i===0?292:i===1?302:i===2?306:0})),dongles:Array.from({length:8},(_,i)=>({ip:i<2?'192.168.50.'+(i+10):'',name:'INVERTER'+(i+1),profile:'packetoffset001',layout:292,cloud_forward:true})),debug:true,mqtt_enabled:false,broker:'',port:1883,mqtt_user:'',base:'solarproxxie',client:'solarproxxie',keepalive:60,retain:true,discovery:true,discovery_prefix:'homeassistant',layout:292,min_interval:5,max_interval:60,stale_seconds:900,on_change:true,log_level:3,probe_enabled:true,probe_ip:'1.1.1.1',dhcp:true,sta_ssid:'',ap_ssid:'SolarProxxie',ap_ip:'192.168.50.1',ap_mask:'255.255.255.0',mask:'255.255.255.0'};
const point={id:'battery_soc',name:'<img src=x onerror=attack()>',suggested_name:'Battery SOC',ha_name:'Battery SOC',value:54,unit:'%',suffix:'inverter/battery_soc',register:184,register2:-1,words:1,packet_offset:244,packet_offset2:null,packet_mapping:'firmware',updated_ms:1000,updated_age_seconds:12,status:'fresh',enabled:true,scale:1,offset:0,evidence:'synthetic test'};
const mqtt={connected:false,device_id:'ghost_test',now_ms:60000,last_connection_ms:0,last_publish_ms:45000,test_result:'not tested',messages_sent:4,failures:0,entities:1,succeeded:1,failed:0,broker:{last_event:'disconnected',event_ms:50000,error_type:0,connect_return_code:0,socket_errno:0,tls_error:0},last_state_publish:{result:'acknowledged by broker',attempt_ms:45000,ack_ms:45100,message_id:12,payload_bytes:18,topic:'solarproxxie/INVERTER1/state',payload:'{"battery_soc":54}'}};
const update={current:'1.2.0',latest:'',available:false,busy:false,bytes:0,status:'Not checked',repository:'martinville/SolarProxxie'};
const status={system:{heap_free:100000,uptime_ms:60000,version:'1.1.0',git_commit:'abc123',build_date:'Sep 23 2026',build_time:'06:45:00',idf:'v5.4.2'},network:{nat_active:true,sta_connected:true,sta_ip:'192.168.1.50',ap_ip:'192.168.50.1',ap_ssid:'SolarProxxie',clients:[],connections:[],offline_mode:false},router:{packets_decoded:1,copy_drops:0,packets_received:1,forward_attempts:1,blocked:0,dongle_detected:true,dongle_ip:'192.168.50.10'},mqtt,dns:{ready:true},internet:{status:'probe reachable',latency_ms:12,offline_mode:false},offline:{enabled:false,server_ready:true,active_connections:0,responses:0}};
const calls=[];let isSetup=false;
let deferLogin=false,finishLogin;
let holdPoints=false,finishPoints;
status.router.dongles=[{dongle_ip:"192.168.50.10",last_valid_age_seconds:12,inverter_serial:"INV1234567",packets_decoded:1}];
status.network.clients=[{ip:'192.168.50.10',mac:'aa:bb:cc:dd:ee:ff'}];
status.network.dongle_gui={active:false,remaining_seconds:0,port:8080,ip:'0.0.0.0'};
async function fetch(url,options={}){calls.push({url,options});const key=url.replace('/api/','');let result;
    if(key==='datapoints/1'&&holdPoints)return new Promise(resolve=>{finishPoints=resolve;});
    if(key==='login'&&deferLogin)return new Promise(resolve=>{finishLogin=resolve;});
    if(options.method==='POST'){const value=options.body?JSON.parse(options.body):{};if(key==='config')Object.assign(config,value);if(key==='dongle-gui')status.network.dongle_gui={active:value.enabled,ip:value.ip||'0.0.0.0',port:8080,remaining_seconds:value.enabled?900:0};if(key==='update'&&value.action==='check')Object.assign(update,{latest:'1.2.1',available:true,bytes:1000000,status:'Update available'});if(key==='update'&&value.action==='install')Object.assign(update,{busy:true,status:'Update scheduled'});result=key==='login'?{csrf:'a'.repeat(64)}:key==='dongle-info'?{serial:'DONGLE123',register_key:'KEY12345',observed_seconds_ago:7}:key==='dongle-gui'?status.network.dongle_gui:key==='update'?{...update}:{ok:true};}
    else if(key==='session')result={setup:isSetup,authenticated:true,csrf:'a'.repeat(64),version:'1.2.0'};
    else if(key==='config')result={...config};
    else if(key==='status'||key==='diagnostics')result=status;
    else if(key==='gateway')result=status.network;
    else if(key==='datapoints'||key.startsWith('datapoints/'))result=[{...point,mqtt_topic:'solarproxxie/INVERTER'+(key.split('/')[1]||1)+'/state',mqtt_key:'battery_soc'}];
    else if(key==='mqtt')result=mqtt;
    else if(key==='update')result={...update};
    else if(key==='packets')result={connections:[],status:{stream_active:false,stream_packets:0,stream_drops:0}};
    else if(key==='scan')result=[{ssid:'Test Wi-Fi',rssi:-52,security:3}];
    else if(key.startsWith('shipped-packet-offsets/')){const slot=Number(key.split('/')[1]);result={version:1,packet_offset:slot,name:`Shipped ${slot}`,layout:292,data_points:[]};}
    else result={};
    return {ok:true,status:200,json:async()=>result,text:async()=>'<script>not executable</script>'};
}
const ctx=vm.createContext({document,console,fetch,setInterval:()=>1,clearInterval:()=>{},setTimeout:()=>1,confirm:()=>true});
vm.runInContext(fs.readFileSync('web/app.js','utf8'),ctx);
const run=code=>vm.runInContext(code,ctx);
const settle=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
    await settle();await settle();assert.match(document.querySelector('main').textContent,/Your energy, observed/);
    assert(document.querySelector('.site-container'),'UI is wrapped in a centered application container');
    assert.equal(document.querySelector('.header-logo').getAttribute('src'),'/logo.svg','Header uses the project logo');
    assert.equal(document.querySelector('.site-container > nav').nextElementSibling.tagName,'MAIN','Navigation sits above the main content');
    assert.equal(document.querySelectorAll('#nav button .icon').length,document.querySelectorAll('#nav button').length,'Every navigation action has a compact SVG icon');
    for(const page of ['Data Points','MQTT','Gateway','Diagnostics','Packets','Firmware','Configuration','About']){await run(`show(${JSON.stringify(page)})`);await settle();assert(document.querySelector('h2'),page);assert(!document.querySelector('main img'),'Escapes untrusted field names');}
    await run('show("Firmware")');await settle();assert.equal(document.querySelectorAll('.firmware-grid > .card').length,2,'Firmware actions use two equal grid cards');document.querySelector('#check-cloud-update').click();await settle();await settle();assert.equal(document.querySelector('#install-cloud-update').hidden,false,'Published update can be installed');assert.match(document.querySelector('#cloud-update-status').textContent,/1\.2\.1/);
    status.router.dongles[0].last_valid_age_seconds=12;status.router.dongles[0].inverter_serial='INV1234567';status.router.configured_layout=292;
    await run('show("Dashboard")');
    assert.equal(document.querySelectorAll('.dashboard-metrics > .card').length,6,'Dashboard uses six compact cards');
    const internet=document.querySelector('.internet-card');
    assert.match(internet.textContent,/InternetOnline1\.1\.1\.1Every 30s · 12 ms/);
    assert(internet.querySelector('.status-light.online'),'Reachable Internet uses the green light');
    status.internet.status='probe did not reply';await run('show("Dashboard")');
    assert.match(document.querySelector('.internet-card').textContent,/InternetOffline/);
    assert(document.querySelector('.internet-card .status-light.offline'),'Failed probe uses the red light');
    status.internet.offline_mode=true;status.network.offline_mode=true;await run('show("Dashboard")');
    assert.match(document.querySelector('.internet-card').textContent,/Local fallback active/);
    assert.match(document.querySelector('main').textContent,/local dongle fallback is active/);
    status.internet.offline_mode=false;status.network.offline_mode=false;
    status.internet.status='probe reachable';
    assert(!document.querySelector('#dongle-details'),'Dongles are not duplicated on Dashboard');
    assert(!document.querySelector('main').textContent.includes('AP clients'));
    assert(!document.querySelector('main').textContent.includes('Full publish'));
    assert(!document.querySelector('main').textContent.includes('copies dropped'));
    assert.match(document.querySelector('main').textContent,/Hosted AP SolarProxxie 192\.168\.50\.1/);
    assert.equal(document.querySelector('#content > .section-card .section-toggle').getAttribute('aria-expanded'),'true','Dashboard health starts open');
    status.router.dongles.push({dongle_ip:'192.168.50.11',inverter_serial:'SECOND123',last_valid_age_seconds:33,packets_decoded:7});
    await run('show("Diagnostics")');
    assert.equal(document.querySelectorAll('#packet-pipeline #dongle-details .inverter-pipeline').length,2);
    assert.match(document.querySelectorAll('.inverter-pipeline')[1].textContent,/SECOND123/);
    assert(document.querySelector('#system-info dl'));assert(!document.querySelector('#content pre'));
    status.router.dongles.pop();
    status.network.connections=[{source:'192.168.50.10',remote_ip:'1.2.3.4',source_port:1000,remote_port:80,packets:4,replies:3,last_activity_ms:58000,state:'Established'}];
    await run('show("Gateway")');
    assert(!document.querySelector('#ap-devices'));
    assert(!document.querySelector('#tcp-devices'));
    assert(!document.querySelector('#content pre'));
    assert.equal(document.querySelectorAll('#dongles tbody tr').length,2);
    assert.match(document.querySelector('#dongles tbody').textContent,/Forwarding/);
    assert.match(document.querySelector('#dongles tbody').textContent,/12s ago/,'Dongle table shows telemetry age');
    assert.match(document.querySelectorAll('#dongles tbody tr')[1].textContent,/Never/,'Unobserved dongles have an explicit update state');
    assert(!document.querySelector('#dongle-gui'),'There is no separate dongle web-interface section');
    assert(!document.querySelector('#gateway-probe-form'));
    assert.equal(document.querySelector('#dongles .section-toggle').getAttribute('aria-expanded'),'true','Dongles starts expanded');
    assert.equal(document.querySelector('#add-dongle').parentElement.className,'section-card-heading','Add action stays in the card header');
    assert.match(document.querySelector('#dongles').textContent,/Legacy 292-byte packet \(292 bytes\)/);
    document.querySelector('[data-dongle-slot="0"]').click();await settle();await settle();
    assert(document.querySelector('#dongle-dialog[open]'));
    assert.match(document.querySelector('#dongle-dialog').textContent,/Connection & captured identity/);
    assert.match(document.querySelector('#dongle-form').textContent,/Newer 302-byte packet \(302 bytes\)/);
    assert.match(document.querySelector('#dongle-form').textContent,/Captured 306-byte packet \(306 bytes\)/);
    assert.match(document.querySelector('#dongle-packet-info').textContent,/DONGLE123/);
    assert.match(document.querySelector('#dongle-packet-info').textContent,/KEY12345/);
    document.querySelector('#dongle-reboot').click();await settle();await settle();
    assert(calls.some(c=>c.url==='/api/dongle-reboot'&&JSON.parse(c.options.body||'{}').ip==='192.168.50.10'));
    document.querySelector('#dongle-gui-toggle').click();await settle();await settle();
    const enable=calls.find(c=>c.url==='/api/dongle-gui');assert.deepEqual(JSON.parse(enable.options.body),{enabled:true,ip:'192.168.50.10'});assert.equal(enable.options.headers['X-CSRF-Token'],'a'.repeat(64));
    assert(document.querySelector('#dongle-dialog[open]'),'Enabling the GUI keeps the modal open');
    assert.equal(document.querySelector('#dongle-gui-open').getAttribute('href'),'http://192.168.1.50:8080/');
    await run('show("Diagnostics")');assert(!document.querySelector('main').textContent.includes('KEY12345'));
    assert(document.querySelector('#ap-devices .device-card dl'));
    assert.match(document.querySelector('#tcp-devices tbody').textContent,/1.2.3.4:80/);
    status.network.connections=[];
    await run('show("Diagnostics")');let details=document.querySelector('#dongle-details');
    assert(document.querySelector('#diagnostic-form [name="debug"]'));
    assert(document.querySelector('#diagnostic-form [name="log_level"]'));
    assert(document.querySelector('#packet-pipeline .section-toggle'),'Diagnostic section can collapse');
    assert.equal(document.querySelector('#system-info .section-toggle').getAttribute('aria-expanded'),'true');
    assert.equal(document.querySelector('#packet-pipeline .section-toggle').getAttribute('aria-expanded'),'false');
    assert.equal(document.querySelector('#dns-info .section-toggle').getAttribute('aria-expanded'),'false');
    assert(document.querySelector('#offline-info'),'Diagnostics shows offline-fallback state and counters');
    assert(!document.querySelector('.inverter-pipeline .section-toggle'),'Inverter records stay open');
    assert.match(details.textContent,/INV1234567/);assert.match(details.textContent,/aa:bb:cc:dd:ee:ff/);
    assert(!document.querySelector('main').textContent.includes('Sign-in performance'));
    status.router.dongles[0].last_valid_age_seconds=901;await run('show("Diagnostics")');assert.match(document.querySelector('#dongle-details').textContent,/Data is stale/);
    status.router.dongles[0].last_valid_age_seconds=null;status.router.dongles[0].inverter_serial='';await run('show("Diagnostics")');assert.match(document.querySelector('#dongle-details').textContent,/Waiting for valid data/);
    status.router.dongles[0].inverter_serial='<img src=x onerror=attack()>';await run('show("Diagnostics")');assert(!document.querySelector('#dongle-details img'));
    status.router.dongles[0].inverter_serial='INV1234567';status.router.dongles[0].last_valid_age_seconds=0;await run('show("Diagnostics")');assert.match(document.querySelector('#dongle-details').textContent,/0 seconds ago/);
    await run('show("Packets")');await settle();
    assert.equal(document.querySelector('#capture-stream').getAttribute('href'),'/api/capture-stream');
    assert.equal(document.querySelector('#capture-stream').getAttribute('download'),'solarproxxie-live.pcap');
    document.querySelector('#capture-stream-stop').click();await settle();await settle();
    assert(calls.some(c=>c.url==='/api/action'&&JSON.parse(c.options.body||'{}').command==='stop-stream'));
    assert.match(document.querySelector('#capture-state').textContent,/Download idle/);
    assert(!document.querySelector('#captured-packets'));
    assert(!document.querySelector('#capture-start'));
    assert(!document.querySelector('#capture-clear'));
    assert(document.querySelector('#pcap-file'),'Browser-local PCAP picker is available');
    run(`(()=>{const b=new Uint8Array(80),v=new DataView(b.buffer);b.set([0xd4,0xc3,0xb2,0xa1,2,0,4,0]);v.setUint32(16,65535,true);v.setUint32(20,101,true);v.setUint32(24,1,true);v.setUint32(32,40,true);v.setUint32(36,40,true);b.set([0x45,0,0,40,0x12,0x34,0x40,0,64,6,0,0,192,168,50,10,8,8,8,8,0x04,0xd2,0,80,0,0,0,1,0,0,0,0,0x50,0x02,0x20,0,0,0,0,0],40);pcapCapture=parsePcap(b.buffer,'sample.pcap');renderPcapCapture();})()`);
    assert.equal(document.querySelectorAll('#pcap-list tbody tr').length,1);
    assert.equal(document.querySelectorAll('#pcap-ip-filter option').length,3,'Filter lists unique source and destination IPs');
    assert.match(document.querySelector('#pcap-list').textContent,/192\.168\.50\.10:1234/);
    assert.match(document.querySelector('#pcap-list').textContent,/8\.8\.8\.8:80/);
    assert.match(document.querySelector('#pcap-detail').textContent,/FlagsSYN/);
    assert.match(document.querySelector('#pcap-detail .hex-dump').textContent,/000000/);
    run(`pcapCapture.packets.push({...pcapCapture.packets[0],source:'10.0.0.1:9000',sourceIp:'10.0.0.1',destination:'192.168.50.10:1234',destinationIp:'192.168.50.10'});renderPcapCapture()`);
    assert.equal(document.querySelectorAll('#pcap-list tbody tr').length,2);
    await document.querySelector('#pcap-ip-filter').onchange({target:{value:'192.168.50.10'}});
    assert.equal(document.querySelectorAll('#pcap-list tbody tr').length,2,'IP filter matches both source and destination');
    assert.match(document.querySelector('#pcap-summary').textContent,/2 matching 192\.168\.50\.10/);
    await document.querySelector('#pcap-ip-filter').onchange({target:{value:'10.0.0.1'}});
    assert.equal(document.querySelectorAll('#pcap-list tbody tr').length,1,'Other IPs are excluded');
    assert.match(document.querySelector('#pcap-list').textContent,/10\.0\.0\.1:9000/);
    assert.match(css,/#pcap-list\s*\{[^}]*max-height:[^}]*overflow:auto/s,'Packet list has a bounded scrolling viewport');
    assert.throws(()=>run(`parsePcap(Uint8Array.from([0x0a,0x0d,0x0d,0x0a,...Array(20).fill(0)]).buffer,'bad.pcapng')`),/PCAPNG/);
    await run('show("Configuration")');for(const key of ['sta_ssid','sta_password','ip','gateway','dns1','admin','admin_password','ap_password'])assert(document.querySelector(`[name="${key}"]`),'Setup fields are editable in Settings');
    assert.equal(document.querySelectorAll('#network-form .form-section').length,4,'Settings are grouped into logical form sections');
    assert(document.querySelector('[name="sta_ssid"]').closest('.form-grid-two'),'Home Wi-Fi credentials share a compact row');
    assert(document.querySelector('[name="ip"]').closest('.form-grid-three'),'Static network fields use a compact grid');
    assert(document.querySelector('[name="admin_password"]').closest('.form-grid-two'),'Administrator credentials share a compact row');
    assert(document.querySelector('#gateway-probe-form [name="probe_ip"]'),'Reachability moved below network settings');
    const unitForm=document.querySelector('#unit-form'),unitSelect=unitForm.querySelector('[name="unit_system"]');
    assert.equal(unitSelect.querySelector('option[selected]').value,'metric','Metric is the default measurement system');
    Object.defineProperty(unitSelect,'value',{configurable:true,get:()=> 'imperial'});
    await unitForm.onsubmit({preventDefault(){},target:unitForm});await settle();
    assert.equal(config.imperial_units,true,'Imperial preference is saved from Settings');
    assert(calls.some(c=>c.url==='/api/config'&&JSON.parse(c.options.body||'{}').imperial_units===true));
    await run('show("About")');const aboutText=document.querySelector('main').textContent;assert.match(aboutText,/Copyright © 2026 Martin Viljoen/);assert.match(aboutText,/GNU General Public License v3\.0 or later/);for(const source of ['sunsniff','kellerza\/sunsynk','ESP-IDF 5.4.2','FreeRTOS Kernel','lwIP','Mbed TLS','cJSON','ESP-MQTT','Linkedom 0.18.12','Protocol evidence'])assert.match(aboutText,new RegExp(source));assert.equal(document.querySelectorAll('.credits-list > div').length,12,'About lists every direct source and dependency group');assert([...document.querySelectorAll('h3')].some(h=>h.textContent==='Security'));assert([...document.querySelectorAll('#content .section-toggle')].every(button=>button.getAttribute('aria-expanded')==='true'),'All About cards start expanded');
    assert.match(document.querySelector('footer').textContent,/COPYRIGHT © 2026 MARTIN VILJOEN/);
    assert.equal(document.querySelector('#firmware-version').textContent,'v1.1.0','Persistent footer shows the running firmware version');
    assert.match(document.querySelector('#build-info').textContent,/Firmware version1\.1\.0/);
    assert.match(document.querySelector('#build-info').textContent,/Build revisionabc123/);
    status.network.dongle_gui={active:false,remaining_seconds:0,port:8080,ip:'0.0.0.0'};
    status.network.clients=[{ip:'192.168.50.10',mac:'aa:bb:cc:dd:ee:ff',ip_source:'arp'},{ip:'192.168.50.12',mac:'11:22:33:44:55:66'}];
    await run('show("Diagnostics")');
    assert(document.querySelector('#ap-devices > .section-card-heading .section-toggle'));
    assert(!document.querySelector('.device-card .section-toggle'),'Individual AP devices stay open');
    assert(document.querySelector('[data-add-client="192.168.50.12"]'),'Unconfigured connected device can be added');
    document.querySelector('[data-add-client="192.168.50.12"]').click();
    assert.equal(document.querySelector('#dongle-form [name="ip"]').value,'192.168.50.12');
    document.querySelector('#dongle-form [name="name"]').value='GARAGE';
    const profileSelect=document.querySelector('#dongle-form [name="profile"]');Object.defineProperty(profileSelect,'value',{configurable:true,get:()=> 'packetoffset003'});
    document.querySelector('#dongle-form [name="cloud_forward"]').checked=false;
    const dongleForm=document.querySelector('#dongle-form');await dongleForm.onsubmit({preventDefault(){},target:dongleForm});await settle();
    assert.equal(config.dongles[2].profile,'packetoffset003','Added dongle keeps its packet-offset setup');
    assert.equal(config.dongles[2].cloud_forward,false,'Cloud forwarding is saved per dongle');
    await run('show("Gateway")');
    assert.match(document.querySelector('#dongles tbody').textContent,/Local only/);
    document.querySelector('[data-dongle-slot="2"]').click();
    document.querySelector('#remove-dongle').click();await settle();await settle();
    assert.equal(config.dongles[2].ip,'','Removing one dongle preserves internal positions');
    const gatewayReads=calls.filter(c=>c.url==='/api/gateway').length;
    await run('show("Diagnostics")');assert.equal(calls.filter(c=>c.url==='/api/gateway').length,gatewayReads+1,'One shared gateway snapshot per refresh');
    await run('show("Data Points")');
    const dataPointCard=document.querySelector('#data-points-card');
    assert(dataPointCard&&dataPointCard.hasAttribute('open'),'Data-point card is collapsible and expanded by default');
    assert.match(dataPointCard.querySelector('summary').textContent,/Data-point values/);
    assert(dataPointCard.querySelector('summary .section-toggle'),'Data-point card uses the shared collapse icon');
    assert(!document.querySelector('#packet-mapping-settings'),'Data points have their own tab');
    document.querySelector('#packet-offsets-tab').click();
    assert(document.querySelector('#packet-mapping-settings'),'Packet mapping upload has its own tab inside Data Points');
    assert(document.querySelector('#data-freshness').compareDocumentPosition(document.querySelector('#packet-mapping-settings'))&2,'Data freshness follows packet-offset setup files');
    assert(!document.querySelector('#packet-mapping-settings').textContent.includes('datapoints.json'));
    for(const number of ['001','002','003'])assert(document.querySelector(`#packet-mapping-settings a[href="/api/packet-offsets/${number}"][download="packetoffset${number}.json"]`));
    assert.equal(document.querySelectorAll('.packet-offset-upload').length,8,'Eight independent setup slots are available');
    assert.equal(document.querySelectorAll('.packet-offset-delete').length,3,'Every active setup is deletable');
    const addSetup=document.querySelector('.packet-offset-upload[data-offset="004"]'),setupFile=document.querySelector('#packet-offset-file-004');
    assert.equal(addSetup.tagName,'LABEL','Add setup uses a native file-picker label');
    assert.equal(addSetup.getAttribute('for'),'packet-offset-file-004');
    Object.defineProperty(setupFile,'files',{configurable:true,value:[{size:100,text:async()=>'{"version":1,"packet_offset":3,"name":"Copied setup","layout":300,"data_points":[]}'}]});
    setupFile.onchange();await settle();await settle();
    for(const action of ['begin','commit'])assert(calls.some(c=>c.url===`/api/packet-offsets/004/${action}`&&c.options.method==='POST'),`Selected setup ${action} is sent automatically`);
    assert.equal(JSON.parse(calls.find(c=>c.url==='/api/packet-offsets/004/begin').options.body).packet_offset,4,'Copying a setup assigns it to the selected slot');
    assert(document.querySelector('#mapping-defaults'),'Shipped mapping files can be restored without a factory reset');
    document.querySelector('#mapping-defaults').click();for(let i=0;i<10;i++)await settle();
    for(const number of ['001','002','003'])assert(calls.some(c=>c.url===`/api/packet-offsets/${number}/commit`&&c.options.method==='POST'),`Restore uploads shipped setup ${number}`);
    assert.match(document.querySelector('#packet-mapping-settings').textContent,/There is no separate shared data-point file/);
    document.querySelector('#data-points-tab').click();await settle();await settle();
    assert.match(document.querySelector('#table').textContent,/Packet byte 244.*firmware/);
    assert.match(document.querySelector('#table').textContent,/12s ago/,'Data point shows a readable last-update age');
    assert.match(document.querySelector('#data-snapshot-status').textContent,/does not poll/i,'Data point page explains snapshot behavior');
    const pointReads=calls.filter(c=>c.url==='/api/datapoints/1').length;
    document.querySelector('#refresh-data-points').click();await settle();await settle();
    assert.equal(calls.filter(c=>c.url==='/api/datapoints/1').length,pointReads+1,'Data points refresh only when requested');
    const chooser=document.querySelector('#inverter-select');Object.defineProperty(chooser,'value',{value:'2'});
    await chooser.onchange({target:chooser});assert.match(document.querySelector('#table').textContent,/solarproxxie\/INVERTER2\/stateJSON key: battery_soc/);
    assert(calls.some(c=>c.url==='/api/datapoints/2'));
    holdPoints=true;
    const staleSelection=document.querySelector('#inverter-select').onchange({target:{value:'1'}});
    await document.querySelector('#inverter-select').onchange({target:{value:'2'}});
    finishPoints({ok:true,status:200,json:async()=>[{...point,mqtt_topic:'solarproxxie/INVERTER1/state',mqtt_key:'battery_soc'}]});
    await staleSelection;holdPoints=false;
    assert.match(document.querySelector('#table').textContent,/solarproxxie\/INVERTER2\/state/,'Older responses cannot relabel another inverter');
    assert(![...document.querySelectorAll('#nav button')].some(button=>button.dataset.page==='Inverter'),'Duplicate Inverters page is absent');
    assert(!document.querySelector('#content [name="profile"]'),'Decoder profile is configured only with each Dongle mapping');
    document.querySelector('#packet-offsets-tab').click();
    assert(document.querySelector('#freshness-form [name="stale_seconds"]'));
    document.querySelector('#freshness-form [name="stale_seconds"]').value='1200';
    await document.querySelector('#freshness-form').onsubmit({preventDefault(){}});
    assert(!document.querySelector('#notice').classList.contains('error'),document.querySelector('#notice').textContent);
    assert.equal(config.stale_seconds,1200,'Shared freshness timeout is saved from Packet Offsets');
    assert.equal(config.dongles[0].profile,'packetoffset001','Data Points does not alter per-dongle setups');
    assert.equal(config.dongles[1].profile,'packetoffset001');
    await run('show("MQTT")');await settle();await settle();assert(document.querySelector('#mqtt-test-entered'));assert(document.querySelector('[name="mqtt_password"]'));
    assert.match(document.querySelector('#mqtt-status').textContent,/Disconnected/);
    assert.match(document.querySelector('#mqtt-status').textContent,/15s ago/,'MQTT timestamps are shown as readable ages');
    assert.match(document.querySelector('#mqtt-status').textContent,/acknowledged by broker/,'MQTT shows the PUBACK result');
    assert.match(document.querySelector('#mqtt-status').textContent,/"battery_soc": 54/,'MQTT shows the last state payload');
    assert.match(document.querySelector('#mqtt-status').textContent,/Telemetry → MQTT pipeline/,'MQTT shows the receive-to-publish pipeline');
    assert.match(document.querySelector('#mqtt-status').textContent,/Receive-to-attempt delay/,'MQTT exposes publish latency');
    const publishButton=document.querySelector('[data-cmd="publish"]');publishButton.click();await settle();await settle();
    assert.match(document.querySelector('#mqtt-action-status').textContent,/Publish requested/,'MQTT action gives visible feedback without vague queue wording');
    assert.equal(document.querySelector('#mqtt').closest('.section-card').querySelector('.section-toggle').getAttribute('aria-expanded'),'true','Broker settings are first');
    assert(document.querySelector('#mqtt-timing-form [name="min_interval"]'));
    assert([...document.querySelectorAll('#content .section-toggle')].every(button=>button.getAttribute('aria-expanded')==='true'),'All MQTT cards start expanded');
    await run('show("Data Points")');document.querySelector('#data-points-tab').click();await settle();await settle();await run('editPoint("battery_soc")');assert.equal(document.querySelector('[name="ha_name"]').value,'Battery SOC');
    isSetup=true;await run('boot()');for(let step=0;step<6;step++){run(`step=${step};wizard()`);assert.match(document.querySelector('h3').textContent,new RegExp(`${step+1} / 6`));}
    run('step=4;wizard()');assert.equal(document.querySelector('[name="admin_password"]').type,'password');
    run('step=5;wizard()');assert.match(document.querySelector('#fields').textContent,/add and manage dongles/i);assert(!document.querySelector('#wizard-add-inverter'));
    await run('show("Logout")');assert(document.querySelector('#login'));
    assert.equal(document.querySelector('.login-logo').getAttribute('src'),'/logo.svg','Login uses the project logo');
    assert.match(document.querySelector('.login-version').textContent,/Firmware v1\.2\.0/,'Login shows the running firmware version');
    isSetup=false;deferLogin=true;
    const form=document.querySelector('#login'),submit=form.querySelector('button');
    form.querySelector('[name="username"]').value='admin';form.querySelector('[name="password"]').value='test-password';
    const event={preventDefault(){},target:form};const pending=form.onsubmit(event);
    assert(submit.disabled);assert.equal(submit.textContent,'Signing in…');assert.equal(form.getAttribute('aria-busy'),'true');
    assert.match(document.querySelector('#login-status').textContent,/Checking your password/);assert(!document.querySelector('#login-status').textContent.includes('10 seconds'));
    const count=calls.filter(c=>c.url==='/api/login').length;await form.onsubmit(event);assert.equal(calls.filter(c=>c.url==='/api/login').length,count,'Duplicate login prevented');
    finishLogin({ok:false,status:401,json:async()=>({error:'Invalid username or password'})});await pending;
    assert(!submit.disabled);assert.equal(form.getAttribute('aria-busy'),null);assert.equal(form.querySelector('[name="password"]').value,'');
    assert.match(document.querySelector('#notice').textContent,/Invalid username/);
    form.querySelector('[name="password"]').value='correct-password';const retry=form.onsubmit(event);
    finishLogin({ok:true,status:200,json:async()=>({csrf:'b'.repeat(64)})});await retry;
    assert.match(document.querySelector('main').textContent,/Your energy, observed/);
    console.log('PASS web: navigation, dongle modal, diagnostics ownership, editable setup settings, login and XSS escaping');
    console.log('DOM integration tests only; visual browser and ESP32 HTTP integration remain hardware/browser checks.');
})().catch(e=>{console.error(e);process.exitCode=1;});
